// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockForkProvider is an autogenerated mock type for the ForkProvider type
type MockForkProvider struct {
	mock.Mock
}

type MockForkProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForkProvider) EXPECT() *MockForkProvider_Expecter {
	return &MockForkProvider_Expecter{mock: &_m.Mock}
}

// ConfigureRemotesForExistingFork provides a mock function with given fields: forkName
func (_m *MockForkProvider) ConfigureRemotesForExistingFork(forkName string) error {
	ret := _m.Called(forkName)

	if len(ret) == 0 {
		panic("no return value specified for ConfigureRemotesForExistingFork")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(forkName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockForkProvider_ConfigureRemotesForExistingFork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureRemotesForExistingFork'
type MockForkProvider_ConfigureRemotesForExistingFork_Call struct {
	*mock.Call
}

// ConfigureRemotesForExistingFork is a helper method to define mock.On call
//   - forkName string
func (_e *MockForkProvider_Expecter) ConfigureRemotesForExistingFork(forkName interface{}) *MockForkProvider_ConfigureRemotesForExistingFork_Call {
	return &MockForkProvider_ConfigureRemotesForExistingFork_Call{Call: _e.mock.On("ConfigureRemotesForExistingFork", forkName)}
}

func (_c *MockForkProvider_ConfigureRemotesForExistingFork_Call) Run(run func(forkName string)) *MockForkProvider_ConfigureRemotesForExistingFork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockForkProvider_ConfigureRemotesForExistingFork_Call) Return(_a0 error) *MockForkProvider_ConfigureRemotesForExistingFork_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockForkProvider_ConfigureRemotesForExistingFork_Call) RunAndReturn(run func(string) error) *MockForkProvider_ConfigureRemotesForExistingFork_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFork provides a mock function with given fields: forkName
func (_m *MockForkProvider) CreateFork(forkName string) error {
	ret := _m.Called(forkName)

	if len(ret) == 0 {
		panic("no return value specified for CreateFork")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(forkName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockForkProvider_CreateFork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFork'
type MockForkProvider_CreateFork_Call struct {
	*mock.Call
}

// CreateFork is a helper method to define mock.On call
//   - forkName string
func (_e *MockForkProvider_Expecter) CreateFork(forkName interface{}) *MockForkProvider_CreateFork_Call {
	return &MockForkProvider_CreateFork_Call{Call: _e.mock.On("CreateFork", forkName)}
}

func (_c *MockForkProvider_CreateFork_Call) Run(run func(forkName string)) *MockForkProvider_CreateFork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockForkProvider_CreateFork_Call) Return(_a0 error) *MockForkProvider_CreateFork_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockForkProvider_CreateFork_Call) RunAndReturn(run func(string) error) *MockForkProvider_CreateFork_Call {
	_c.Call.Return(run)
	return _c
}

// ForkExists provides a mock function with given fields: forkName
func (_m *MockForkProvider) ForkExists(forkName string) (bool, error) {
	ret := _m.Called(forkName)

	if len(ret) == 0 {
		panic("no return value specified for ForkExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(forkName)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(forkName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(forkName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockForkProvider_ForkExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForkExists'
type MockForkProvider_ForkExists_Call struct {
	*mock.Call
}

// ForkExists is a helper method to define mock.On call
//   - forkName string
func (_e *MockForkProvider_Expecter) ForkExists(forkName interface{}) *MockForkProvider_ForkExists_Call {
	return &MockForkProvider_ForkExists_Call{Call: _e.mock.On("ForkExists", forkName)}
}

func (_c *MockForkProvider_ForkExists_Call) Run(run func(forkName string)) *MockForkProvider_ForkExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockForkProvider_ForkExists_Call) Return(_a0 bool, _a1 error) *MockForkProvider_ForkExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForkProvider_ForkExists_Call) RunAndReturn(run func(string) (bool, error)) *MockForkProvider_ForkExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemoteConfiguration provides a mock function with no fields
func (_m *MockForkProvider) GetRemoteConfiguration() (map[string]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRemoteConfiguration")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockForkProvider_GetRemoteConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoteConfiguration'
type MockForkProvider_GetRemoteConfiguration_Call struct {
	*mock.Call
}

// GetRemoteConfiguration is a helper method to define mock.On call
func (_e *MockForkProvider_Expecter) GetRemoteConfiguration() *MockForkProvider_GetRemoteConfiguration_Call {
	return &MockForkProvider_GetRemoteConfiguration_Call{Call: _e.mock.On("GetRemoteConfiguration")}
}

func (_c *MockForkProvider_GetRemoteConfiguration_Call) Run(run func()) *MockForkProvider_GetRemoteConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockForkProvider_GetRemoteConfiguration_Call) Return(_a0 map[string]string, _a1 error) *MockForkProvider_GetRemoteConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForkProvider_GetRemoteConfiguration_Call) RunAndReturn(run func() (map[string]string, error)) *MockForkProvider_GetRemoteConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// IsRepositoryFork provides a mock function with no fields
func (_m *MockForkProvider) IsRepositoryFork() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRepositoryFork")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockForkProvider_IsRepositoryFork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRepositoryFork'
type MockForkProvider_IsRepositoryFork_Call struct {
	*mock.Call
}

// IsRepositoryFork is a helper method to define mock.On call
func (_e *MockForkProvider_Expecter) IsRepositoryFork() *MockForkProvider_IsRepositoryFork_Call {
	return &MockForkProvider_IsRepositoryFork_Call{Call: _e.mock.On("IsRepositoryFork")}
}

func (_c *MockForkProvider_IsRepositoryFork_Call) Run(run func()) *MockForkProvider_IsRepositoryFork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockForkProvider_IsRepositoryFork_Call) Return(_a0 bool, _a1 error) *MockForkProvider_IsRepositoryFork_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockForkProvider_IsRepositoryFork_Call) RunAndReturn(run func() (bool, error)) *MockForkProvider_IsRepositoryFork_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultRepository provides a mock function with given fields: repo
func (_m *MockForkProvider) SetDefaultRepository(repo string) error {
	ret := _m.Called(repo)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultRepository")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(repo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockForkProvider_SetDefaultRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultRepository'
type MockForkProvider_SetDefaultRepository_Call struct {
	*mock.Call
}

// SetDefaultRepository is a helper method to define mock.On call
//   - repo string
func (_e *MockForkProvider_Expecter) SetDefaultRepository(repo interface{}) *MockForkProvider_SetDefaultRepository_Call {
	return &MockForkProvider_SetDefaultRepository_Call{Call: _e.mock.On("SetDefaultRepository", repo)}
}

func (_c *MockForkProvider_SetDefaultRepository_Call) Run(run func(repo string)) *MockForkProvider_SetDefaultRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockForkProvider_SetDefaultRepository_Call) Return(_a0 error) *MockForkProvider_SetDefaultRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockForkProvider_SetDefaultRepository_Call) RunAndReturn(run func(string) error) *MockForkProvider_SetDefaultRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockForkProvider creates a new instance of MockForkProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForkProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForkProvider {
	mock := &MockForkProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
