# SPDX-FileCopyrightText: Copyright (c) 2020 Koninklijke Philips N.V, https://www.philips.com
# Source: https://github.com/marketplace/actions/repolinter
# SPDX-License-Identifier: MIT


name: Lint repository
on: [push]

jobs:
  repo-lint:
    name: "repolint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Test repolinter
        uses: philips-labs/github-action-repolinter@master
