---
name: sonar-branch-analysis

on:
  pull_request:
    types: [closed]
    branches: ["main"]

env:
  GO_VERSION: 1.21.5
  NODE_VERSION: 18.x

jobs:
  verify:
    if: ${{ github.event.pull_request.merged == true && vars.IS_INDITEXTECH_REPO == 'true' }}
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go version
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verify
        run: |
          make verify

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.branch.name=main
